# Generated by Django 5.2.4 on 2025-09-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_customer_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='branchname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
