# Generated by Django 5.2.4 on 2025-09-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_signup_branchname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
